### ISSUE TITLE
Auto queue

### ISSUE THREAD

**Issue by louikwar** [iholston/lol-accept#1]
Could you add an auto queue option?

**Comment by iholston** [comment]
Can you elaborate? The program accepts queues automatically

**Comment by bhodrolok** [comment]
Think what they are requesting for is the option to start a queue automatically instead of manually pressing the 'Find Match' button in the lobby.
![image](https://github.com/iholston/heimerdinger/assets/51386657/320ddc2f-ebb6-47cd-ac77-47c1f5334d37)

After some trial and error, looks like sending a `POST` request to the `/lol-lobby/v2/lobby/matchmaking/search` endpoint solves this. Want me to open a PR?

@iholston

**Comment by iholston** [comment]
@bhodrolok i appreciate the update. However, I specifically did not add this feature because it makes changing the lobby and/or setting roles rather difficult.
